name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug SSH Connection
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/your_private_key webserver@93.158.211.7 -p 2222 "ls /var/www"

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa.pub webserver@93.158.211.7 -p 2222 "ls /var/www"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WEBSERVER_KEY }}          

