name: Deploy to Server

on:
  push:
    branches:
      - main  # Trigger bij elke push naar de 'main'-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Haal de repository op
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Voeg de private SSH-sleutel toe
      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # 3. Voeg de server aan de lijst van bekende hosts toe
      - name: Add Server to Known Hosts
        run: |
          ssh-keyscan -p 2222 -H 93.158.211.7 >> ~/.ssh/known_hosts

      # 4. Kopieer de bestanden naar de server
      - name: Deploy Files to Server
        run: |
          scp -P 2222 -o StrictHostKeyChecking=no styles.css scripts.js index.html webserver@93.158.211.7:/var/www/GSN/

      # 5. Controleer of bestanden succesvol zijn overgezet
      - name: Verify Deployment
        run: |
          ssh -p 2222 -o StrictHostKeyChecking=no webserver@93.158.211.7 "ls -l /var/www/GSN"
          echo "Hallo"

      # 6. Log activiteit naar GitHub
      - name: Log Deployment Activity
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_KEY }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
          -d '{"body": "Deployment successful on `date`"}' \
          https://api.github.com/repos/${{ github.repository }}/issues/1/comments
