name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Test
        run: |
          echo "Running tests..."
          ./run-tests.sh

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no webserver@93.158.211.7 -p 2222 "cd /var/www/GSN && git pull origin main && ./deploy.sh"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.WEBSERVER_KEY }}
